'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReferenceCustomer
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/ConvergeTest.Service"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataValueField As System.Data.DataTable
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataValue() As System.Data.DataTable
            Get
                Return Me.DataValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataValueField, value) <> true) Then
                    Me.DataValueField = value
                    Me.RaisePropertyChanged("DataValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReferenceCustomer.IServiceCustomer")>  _
    Public Interface IServiceCustomer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/InsertCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/InsertCustomerResponse")>  _
        Function InsertCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/InsertCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/InsertCustomerResponse")>  _
        Function InsertCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/UpdateCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/UpdateCustomerResponse")>  _
        Function UpdateCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/UpdateCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/UpdateCustomerResponse")>  _
        Function UpdateCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/DeleteCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/DeleteCustomerResponse")>  _
        Function DeleteCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/DeleteCustomer", ReplyAction:="http://tempuri.org/IServiceCustomer/DeleteCustomerResponse")>  _
        Function DeleteCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/GetData", ReplyAction:="http://tempuri.org/IServiceCustomer/GetDataResponse")>  _
        Function GetData() As ServiceReferenceCustomer.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/GetData", ReplyAction:="http://tempuri.org/IServiceCustomer/GetDataResponse")>  _
        Function GetDataAsync() As System.Threading.Tasks.Task(Of ServiceReferenceCustomer.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/GetAddressData", ReplyAction:="http://tempuri.org/IServiceCustomer/GetAddressDataResponse")>  _
        Function GetAddressData(ByVal customerId As Integer) As ServiceReferenceCustomer.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/GetAddressData", ReplyAction:="http://tempuri.org/IServiceCustomer/GetAddressDataResponse")>  _
        Function GetAddressDataAsync(ByVal customerId As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceCustomer.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/InsertAddress", ReplyAction:="http://tempuri.org/IServiceCustomer/InsertAddressResponse")>  _
        Function InsertAddress(ByVal address As ConvergeTest.Entities.Address) As ConvergeTest.Common.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceCustomer/InsertAddress", ReplyAction:="http://tempuri.org/IServiceCustomer/InsertAddressResponse")>  _
        Function InsertAddressAsync(ByVal address As ConvergeTest.Entities.Address) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceCustomerChannel
        Inherits ServiceReferenceCustomer.IServiceCustomer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceCustomerClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceCustomer.IServiceCustomer)
        Implements ServiceReferenceCustomer.IServiceCustomer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function InsertCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result Implements ServiceReferenceCustomer.IServiceCustomer.InsertCustomer
            Return MyBase.Channel.InsertCustomer(customer)
        End Function
        
        Public Function InsertCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result) Implements ServiceReferenceCustomer.IServiceCustomer.InsertCustomerAsync
            Return MyBase.Channel.InsertCustomerAsync(customer)
        End Function
        
        Public Function UpdateCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result Implements ServiceReferenceCustomer.IServiceCustomer.UpdateCustomer
            Return MyBase.Channel.UpdateCustomer(customer)
        End Function
        
        Public Function UpdateCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result) Implements ServiceReferenceCustomer.IServiceCustomer.UpdateCustomerAsync
            Return MyBase.Channel.UpdateCustomerAsync(customer)
        End Function
        
        Public Function DeleteCustomer(ByVal customer As ConvergeTest.Entities.Customer) As ConvergeTest.Common.Result Implements ServiceReferenceCustomer.IServiceCustomer.DeleteCustomer
            Return MyBase.Channel.DeleteCustomer(customer)
        End Function
        
        Public Function DeleteCustomerAsync(ByVal customer As ConvergeTest.Entities.Customer) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result) Implements ServiceReferenceCustomer.IServiceCustomer.DeleteCustomerAsync
            Return MyBase.Channel.DeleteCustomerAsync(customer)
        End Function
        
        Public Function GetData() As ServiceReferenceCustomer.CompositeType Implements ServiceReferenceCustomer.IServiceCustomer.GetData
            Return MyBase.Channel.GetData
        End Function
        
        Public Function GetDataAsync() As System.Threading.Tasks.Task(Of ServiceReferenceCustomer.CompositeType) Implements ServiceReferenceCustomer.IServiceCustomer.GetDataAsync
            Return MyBase.Channel.GetDataAsync
        End Function
        
        Public Function GetAddressData(ByVal customerId As Integer) As ServiceReferenceCustomer.CompositeType Implements ServiceReferenceCustomer.IServiceCustomer.GetAddressData
            Return MyBase.Channel.GetAddressData(customerId)
        End Function
        
        Public Function GetAddressDataAsync(ByVal customerId As Integer) As System.Threading.Tasks.Task(Of ServiceReferenceCustomer.CompositeType) Implements ServiceReferenceCustomer.IServiceCustomer.GetAddressDataAsync
            Return MyBase.Channel.GetAddressDataAsync(customerId)
        End Function
        
        Public Function InsertAddress(ByVal address As ConvergeTest.Entities.Address) As ConvergeTest.Common.Result Implements ServiceReferenceCustomer.IServiceCustomer.InsertAddress
            Return MyBase.Channel.InsertAddress(address)
        End Function
        
        Public Function InsertAddressAsync(ByVal address As ConvergeTest.Entities.Address) As System.Threading.Tasks.Task(Of ConvergeTest.Common.Result) Implements ServiceReferenceCustomer.IServiceCustomer.InsertAddressAsync
            Return MyBase.Channel.InsertAddressAsync(address)
        End Function
    End Class
End Namespace
